### ISSUE TITLE
wont start in Ubuntu 24.04

### ISSUE THREAD

**Issue by tatrapikao** [xuancong84/indicator-cpufreq#5]
```
Traceback (most recent call last):
  File "/usr/bin/indicator-cpufreq", line 85, in <module>
    ind = MyIndicator(options.show_frequency)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/indicator_cpufreq/indicator.py", line 78, in __init__
    menu_item = Gtk.RadioMenuItem.new_with_label(group, readable_frequency(freq))
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/indicator_cpufreq/indicator.py", line 34, in readable_frequency
    label = _("%s GHz") % locale.format(_("%.2f"), f / 1.0e6)
                          ^^^^^^^^^^^^^
AttributeError: module 'locale' has no attribute 'format'. Did you mean: '_format'?

```
is what happens when i try to start it on xubuntu 24.04.

**Comment by xuancong84** [comment]
Blame the stupid developer of Python locale package, why they make such a stupid change? Just to show that they have contributed something to the repo?

**Comment by NJNataren** [comment]
I have the exact same issue @tatrapikao

**Comment by xuancong84** [comment]
I have committed the fix, please try again. I will use Ubuntu 22.04 for at least another 3 years.
